---

- name: Create Django docker image
  docker_image:
    name: stn_django
    dockerfile: "{{ role_path }}/files/django/Dockerfile"
    path: "{{ stn_path }}"

- name: Start postgresql
  docker_container:
    name: stn_postgresql-1
    image: postgres:9.3
    exposed_ports:
      - 5432
    published_ports:
      - 5432
    volumes:
      - "{{ stn_path }}:/django"
    state: started
    env:
      POSTGRES_PASSWORD: "{{ stn_postgresql_password }}"
      POSTGRES_USER: "{{ stn_postgresql_username }}"
      POSTGRES_DB: securethenews_db_1
    user: postgres
  register: pg_container_results

#####

# - name: If grsec, add paxflags cmd to node
#   set_fact:
#     node_grsec_image: "node_grsec"
#   when: ansible_kernel.endswith('grsec')
#
# - name: Build node image with pax flags
#   docker_image:
#     name: "node_grsec:{{ stn_node_tag }}"
#     # Reuse custom NodeJS Dockerfile from CI
#     dockerfile: "{{ role_path }}/files/node/Dockerfile"
#     path: "{{ stn_path }}"
#     tag: "{{ stn_node_tag }}"
#
# - name: Purge existing node container wait flag
#   file:
#     state: absent
#     path: "{{ stn_path }}./.node_complete"
#
# - name: Start node
#   docker_container:
#     name: stn_node
#     image: "{{ node_grsec_image|default('node') }}:{{ stn_node_tag }}"
#     volumes:
#       - "{{ stn_path }}:/django"
#     state: started
#     working_dir: /django
#     command: /bin/ash -c "npm install && touch .node_complete && gulp watch"
#     user: node
#     recreate: yes
#
# - name: Wait for node to finish installing deps
#   wait_for:
#     path: "{{ stn_path }}/.node_complete"

#####

- name: Build node image with python
  docker_image:
    name: "stn_node:{{ stn_node_tag }}"
    dockerfile: "{{ role_path }}/files/node/Dockerfile"
    path: "{{ stn_path }}"
    tag: "{{ stn_node_tag }}"

- name: Purge existing node container wait flag
  file:
    state: absent
    path: "{{ stn_path }}/.node_complete"

- name: Start node
  docker_container:
    name: stn_node-1
    image: "stn_node:{{ stn_node_tag }}"
    volumes:
      - "{{ stn_path }}:/django"
    state: started
    working_dir: /django
    command: /bin/ash -c "npm install && touch .node_complete && gulp watch"
    user: node
    recreate: yes

- name: Wait for node to finish installing deps
  wait_for:
    path: "{{ stn_path }}/.node_complete"
    timeout: 600

#####

- name: Start Django server
  docker_container:
    name: stn_django-1
    image: stn_django
    volumes:
      - "{{ stn_path }}:/var/www/django"
    state: started
    exposed_ports:
      - 8000
    published_ports:
      - "8000:{{ stn_public_port}}"
    working_dir: /var/www/django
    interactive: true
    tty: true
    # command: /bin/bash -c "sleep 30; ./manage.py migrate; ./manage.py runserver 0.0.0.0:8000"
    command: /bin/bash -c "sleep 30; ./manage.py migrate; gunicorn securethenews.wsgi:application --bind 0.0.0.0:8000"
    user: gcorn
    env:
      DJANGO_SETTINGS_MODULE: securethenews.settings.production
      DJANGO_DB_PASSWORD: "{{ stn_postgresql_password }}"
      DJANGO_DB_USER: "{{ stn_postgresql_username }}"
      DJANGO_DB_NAME: securethenews_db_1
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: stn_postgresql-1
      DJANGO_SECRET_KEY: "{{ stn_django_secret_key }}"
      DJANGO_ALLOWED_HOSTS: "{{ stn_django_allowed_hosts }}"
      DJANGO_BASE_URL: "http://{{ stn_django_base_url }}"
      DJANGO_CSRF_TRUSTED_ORIGINS: "{{ stn_django_csrf_trusted_origins }}"
      # DJANGO_STATIC_ROOT: "{{ stn_django_static_root }}"
      # DJANGO_MEDIA_ROOT: "{{ stn_django_media_root }}"
      DJANGO_ES_HOST: "{{ stn_django_es_host }}"
      DJANGO_ES_CA_PATH: "{{ stn_django_es_ca_path }}"
    recreate: yes

#####

# - name: Slap paxflags onto pshtt and python when under grsec
#   command: docker exec -u root stn-django /bin/bash -c "paxctl -Cm $(which python)"
#   when: ansible_kernel.endswith('grsec')

#####

- name: Link containers through Docker network
  docker_network:
    name: stn_network
    connected:
      - stn_postgresql-1
      - stn_django-1
      - stn_node-1
    state: present
    force: yes

- name: Wait for Django runserver to come up
  uri:
    url: "http://{{ stn_public_host }}:{{ stn_public_port }}"
    method: GET
    status_code: 200
  register: uri_scrape_result
  until: uri_scrape_result.status == 200
  retries: 10
  delay: 20

- debug:
    msg: "Up at http://{{ stn_public_host }}:{{ stn_public_port }}."
