---

stn_node_tag: 4.8.2-alpine
stn_nginx_tag: 1.13.5

stn_public_port: 8000
stn_public_host: "{{ ansible_default_ipv4.address }}"

stn_path: "{{ base_path }}/security-securethenews"
stn_results_path: "{{ base_path }}/results"

stn_django_secret_key:
stn_django_allowed_hosts: "localhost {{ stn_public_host }}"
stn_django_base_url: "{{ stn_public_host }}"
stn_django_csrf_trusted_origins:
# stn_django_static_root:
# stn_django_media_root:
stn_django_es_host:
stn_django_es_ca_path:
