---

- hosts: all

  vars:
    ds_path: "{{ playbook_dir }}/domain-scan"
    ds_results_path: "{{ playbook_dir }}/results"
    ds_domains_file: "{{ playbook_dir }}/domains.csv"

    stn_path: "{{ playbook_dir }}/security-securethenews"

    stn_ds_cron_import: false

  roles:
    - domain-scan
    - securethenews
    - stn_ds_import
