---

- hosts: all

  vars:
    base_path: "{{ playbook_dir }}"
    ds_domains_file: "{{ playbook_dir }}/files/domains.csv"

    stn_postgresql_password: securethenewspassword
    stn_postgresql_username: securethenews

    stn_cron: false

  pre_tasks:
    - name: Create shared domain-scan and securethenews dir
      file:
        path: "{{ base_path }}/results"
        state: directory

    - name: Template import script
      template:
        src: import.py.j2
        dest: "{{ base_path }}/results/import.py"
        mode: 0755

  roles:
    # - domain-scan
    # - securethenews

  tasks:
    - name: Update data every hour
      cron:
        name: "update stn data"
        minute: "0"
        hour: "*"
        job: "{{ base_path }}/results/import.py"
      when: stn_cron == true

    - name: Update data now
      shell: "python {{ base_path }}/results/import.py"
      when: stn_cron == false
