---

- name: Create domain-scan docker image
  docker_image:
    name: domain_scan
    path: "{{ ds_path }}"

- name: Copy domains list
  copy:
    src: "{{ ds_domains }}"
    dest: "{{ ds_results_path }}/domains.csv"

- name: Purge existing ds container wait flag
  file:
    state: absent
    path: "{{ ds_results_path }}/.ds_complete"

- name: Start domain-scan
  docker_container:
    name: domain_scan-1
    image: domain_scan
    volumes:
      - "{{ ds_results_path }}:/home/scanner/cache/"
    entrypoint: ''
    command: /bin/sh -c "/home/scanner/scan --scan=pshtt /home/scanner/cache/domains.csv ; touch /home/scanner/cache/.ds_complete"
    # command: /bin/sh -c "sudo -E -u scanner -H bash -l -s ./scan --scan=pshtt ./cache/domains.csv ; sudo -E -u scanner -H bash -l -s touch ./cache/.ds_complete"
    state: started

- name: Wait for ds to finish scanning
  wait_for:
    path: "{{ ds_results_path }}/.ds_complete"
    timeout: 600
