---

- name: Create shared domain-scan and securethenews dir
  file:
    path: "{{ ds_results_path }}"
    state: directory

- name: Template import script
  template:
    src: import.py.j2
    dest: "{{ ds_results_path }}/import.py"
    mode: 0755

- name: Update data every hour
  cron:
    name: "update stn data"
    minute: "0"
    hour: "*"
    job: "{{ ds_results_path }}/import.py"
  when: stn_ds_cron_import == true

- name: Update data now
  shell: "python {{ ds_results_path }}/import.py"
  when: stn_ds_cron_import == false
